"use client";

import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Check, Dices } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { useUpdateProfile } from "@/hooks/useProfile";

/**
 * Snapchat-style avatar picker. Avatars are generated by DiceBear (free,
 * no API key) — pick a style, pick a face, done. The chosen URL is saved
 * to user_profiles.avatar_url and shows up everywhere (friends, leaderboard,
 * map, polls).
 */

const STYLES = [
  { id: "adventurer", label: "Adventurer" },
  { id: "big-smile", label: "Smiley" },
  { id: "lorelei", label: "Doodle" },
  { id: "bottts", label: "Robo" },
  { id: "fun-emoji", label: "Emoji" },
] as const;

const SEEDS = [
  "aisha", "arjun", "bunty", "chai", "dhruv", "esha", "faiz", "gully",
  "hero", "ishita", "jugad", "kabir", "laddu", "meera", "nakul", "oye",
  "pihu", "queen", "rohan", "sachin", "tara", "udaan", "vibe", "zoya",
];

export function avatarUrl(style: string, seed: string): string {
  return `https://api.dicebear.com/9.x/${style}/svg?seed=${encodeURIComponent(seed)}&backgroundColor=6C63FF,FF6584,43D98C,FFB347&backgroundType=gradientLinear`;
}

export function AvatarPicker({
  open,
  onClose,
  currentUrl,
}: {
  open: boolean;
  onClose: () => void;
  currentUrl: string | null;
}) {
  const updateProfile = useUpdateProfile();
  const [style, setStyle] = useState<string>(STYLES[0].id);
  const [selected, setSelected] = useState<string | null>(currentUrl);
  const [extraSeeds, setExtraSeeds] = useState<string[]>([]);

  const seeds = useMemo(() => [...SEEDS, ...extraSeeds], [extraSeeds]);

  const shuffle = () => {
    const random = Array.from({ length: 8 }, () =>
      Math.random().toString(36).slice(2, 8)
    );
    setExtraSeeds(random);
  };

  const save = async () => {
    await updateProfile.mutateAsync({ avatar_url: selected });
    onClose();
  };

  return (
    <Modal open={open} onClose={onClose} title="Pick your avatar">
      {/* Style tabs */}
      <div className="flex gap-2 overflow-x-auto no-scrollbar -mx-1 px-1 mb-4">
        {STYLES.map((s) => (
          <button
            key={s.id}
            onClick={() => setStyle(s.id)}
            className={`shrink-0 px-3.5 py-2 rounded-full text-xs font-bold border transition-colors ${
              style === s.id
                ? "bg-primary-dim border-primary text-primary"
                : "border-line text-ink-dim"
            }`}
          >
            {s.label}
          </button>
        ))}
      </div>

      {/* Avatar grid */}
      <div className="grid grid-cols-4 gap-3 max-h-72 overflow-y-auto pr-1 mb-4">
        {seeds.map((seed) => {
          const url = avatarUrl(style, seed);
          const active = selected === url;
          return (
            <motion.button
              key={`${style}-${seed}`}
              whileTap={{ scale: 0.85 }}
              onClick={() => setSelected(url)}
              aria-label={`Avatar ${seed}`}
              aria-pressed={active}
              className={`relative aspect-square rounded-full overflow-hidden border-2 transition-colors ${
                active ? "border-primary" : "border-transparent"
              }`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={url} alt="" className="w-full h-full" loading="lazy" />
              {active && (
                <span className="absolute inset-0 grid place-items-center bg-black/30">
                  <Check className="h-6 w-6 text-white" />
                </span>
              )}
            </motion.button>
          );
        })}
      </div>

      <div className="flex gap-2">
        <Button variant="secondary" onClick={shuffle} aria-label="More random avatars">
          <Dices className="h-4 w-4" /> Shuffle
        </Button>
        <Button
          className="flex-1"
          onClick={save}
          loading={updateProfile.isPending}
          disabled={!selected || selected === currentUrl}
        >
          Save avatar
        </Button>
      </div>
      {currentUrl && (
        <button
          onClick={async () => {
            setSelected(null);
            await updateProfile.mutateAsync({ avatar_url: null });
            onClose();
          }}
          className="w-full min-h-[44px] mt-1 text-xs text-ink-dim hover:text-danger"
        >
          Remove avatar (use initial)
        </button>
      )}
    </Modal>
  );
}
